# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded ant.tcl 1 [list source [file join $dir ant.tcl]]
package ifneeded backup.tcl 1 [list source [file join $dir backup.tcl]]
package ifneeded c.tcl 1 [list source [file join $dir c.tcl]]
package ifneeded clearcase.tcl 1 [list source [file join $dir clearcase.tcl]]
package ifneeded colorme.tcl 1 [list source [file join $dir colorme.tcl]]
package ifneeded eiffel.tcl 1 [list source [file join $dir eiffel.tcl]]
package ifneeded globals.tcl 1 [list source [file join $dir globals.tcl]]
package ifneeded grep.tcl 1 [list source [file join $dir grep.tcl]]
package ifneeded greputils.tcl 1 [list source [file join $dir greputils.tcl]]
package ifneeded help.tcl 1 [list source [file join $dir help.tcl]]
package ifneeded marks.tcl 1 [list source [file join $dir marks.tcl]]
package ifneeded sgml.tcl 1 [list source [file join $dir sgml.tcl]]
package ifneeded tcl.tcl 1 [list source [file join $dir tcl.tcl]]
package ifneeded tests.tcl 1 [list source [file join $dir tests.tcl]]
package ifneeded tk.tcl 1 [list source [file join $dir tk.tcl]]
package ifneeded vc.tcl 1 [list source [file join $dir vc.tcl]]
package ifneeded windows.tcl 1 [list source [file join $dir windows.tcl]]
package ifneeded www.tcl 1 [list source [file join $dir www.tcl]]
package ifneeded xml.tcl 1 [list source [file join $dir xml.tcl]]
